(function () {
  const { videos, profile } = window.PORTFOLIO_DATA;
  const icon = name => ({ play: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="m9 7 8 5-8 5V7Z"/></svg>', arrow: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M5 12h14M13 6l6 6-6 6" stroke-linecap="round" stroke-linejoin="round"/></svg>', close: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 6l12 12M18 6 6 18" stroke-linecap="round"/></svg>' })[name];
  const media = (v, preview = false) => v.type === 'gif' ? `<img src="${v.url}" alt="${v.title}">` : v.type === 'chunked' ? (preview ? `<div class="video-placeholder">MEIYIYOU<br><span>LOGO MOTION</span></div>` : `<video class="chunked-video" controls autoplay playsinline></video>`) : `<video src="${v.url}" ${preview ? 'autoplay muted loop playsinline preload="metadata"' : 'controls autoplay playsinline'}></video>`;
  const card = v => `<article class="work-card" data-id="${v.id}" tabindex="0" aria-label="播放 ${v.title}"><div class="work-media">${media(v, true)}<span class="play">${icon('play')}</span><span class="work-index">0${v.id}</span></div><div class="work-info"><div><p>${v.category}</p><h3>${v.title}</h3></div><span>${v.date}</span></div></article>`;
  document.getElementById('root').innerHTML = `<div id="top"><header class="header wrap"><a class="brand" href="#top">ZHANG<span>®</span></a><nav><a href="#works">作品</a><a href="#about">关于</a><a href="#contact">联系</a></nav></header><main><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">PORTFOLIO / 2026</p><h1>让静态的想法，<br><em>动起来。</em></h1><p class="intro">我是 zhang，一名专注于品牌与界面动效的设计师。<br>用简洁、有节奏的画面，让视觉更有记忆点。</p><a class="round-link" href="#works">查看作品 ${icon('arrow')}</a></div><div class="hero-mark"><span>ZHANG</span><i></i><b>01</b></div></section><section class="works wrap" id="works"><div class="section-label"><p>SELECTED WORKS</p><span>03 / 作品</span></div><div class="work-grid">${videos.map(card).join('')}</div></section><section class="about" id="about"><div class="wrap about-grid"><div><p class="eyebrow">ABOUT ME</p><h2>专注于让品牌与<br><em>界面拥有节奏。</em></h2></div><div class="about-text"><div class="avatar-placeholder">头像<br>位置</div><p>目前持续探索 MG 动画、品牌 Logo 动效与 UI 动效设计。每一帧都从内容出发，寻找清晰、自然且有趣的表达方式。</p></div></div></section><section class="contact wrap" id="contact"><p class="eyebrow">LET'S CONNECT</p><h2>有项目想合作？<br><em>欢迎联系我。</em></h2><div class="contact-details"><a href="tel:${profile.phone}"><small>电话</small>${profile.phone}</a><div><small>微信</small>${profile.wechat}</div></div></section></main><footer class="wrap"><span>© 2026 ZHANG</span><a href="#top">回到顶部 ↑</a></footer></div><div id="modal-root"></div>`;
  const close = () => { document.getElementById('modal-root').innerHTML = ''; document.body.classList.remove('locked'); };
  const open = id => { const v = videos.find(item => item.id === Number(id)); document.getElementById('modal-root').innerHTML = `<div class="modal"><section><button class="close" aria-label="关闭">${icon('close')}</button><div class="modal-media">${media(v)}</div><div class="modal-info"><p>${v.category} · ${v.date}</p><h3>${v.title}</h3><span>${v.description}</span></div></section></div>`; document.body.classList.add('locked'); if(v.type === 'chunked'){const player=document.querySelector('.chunked-video');Promise.all(v.chunks.map(url=>fetch(url).then(response=>response.arrayBuffer()))).then(parts=>{player.src=URL.createObjectURL(new Blob(parts,{type:'video/mp4'}));player.play();}).catch(()=>{player.outerHTML='<p class="video-error">视频暂时无法加载，请刷新后重试。</p>';});} document.querySelector('.close').onclick = close; document.querySelector('.modal').onclick = e => { if (e.target === e.currentTarget) close(); }; };
  document.querySelector('.work-grid').onclick = event => { const item = event.target.closest('.work-card'); if (item) open(item.dataset.id); };
  document.querySelector('.work-grid').onkeydown = event => { if (event.key === 'Enter' && event.target.classList.contains('work-card')) open(event.target.dataset.id); };
  document.onkeydown = event => { if (event.key === 'Escape') close(); };
})();
